name: Rails CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password # Must be non-empty.
          POSTGRES_DB: app_prototype_test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16.18.1'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install JavaScript dependencies
      run: yarn install

    - name: Set up database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: password
      run: |
        bin/rails db:create db:schema:load

    - name: Load seeds
      run: bin/rails db:seed

    - name: Load sample data
      run: bin/rails db:sample_data

  rubocop:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    - name: RuboCop check
      run: bundle exec rubocop

  rspec:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby and Node
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install ChromeDriver
      uses: browser-actions/setup-chromedriver@v1

    - name: Install JavaScript dependencies
      run: yarn install

    - name: Set up database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: password
      run: |
        bin/rails db:create db:schema:load

    - name: Precompile assets
      run: bin/rails assets:precompile

    - name: RSpec Tests
      run: bundle exec rspec

    # Save screenshots for debugging
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: ./tmp/screenshots
