name: Rails CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password # Must be non-empty.
          POSTGRES_DB: app_prototype_test
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Yarn and JavaScript dependencies
      run: |
        npm install -g yarn
        yarn install

    - name: Set up database
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: password
      run: |
        bin/rails db:create db:schema:load db:seed

    - name: Set up Chrome
      uses: webfactory/setup-chrome@v1.0.1
      with:
        chrome-version: stable

    - name: Execute RSpec Tests
      env:
        RAILS_ENV: test
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: password
      run: bundle exec rspec
